window.HOTELS=[
 {
  "id": "mermaid-hotel-vlore",
  "stop": 1,
  "name": "Mermaid (Sirena) Hotel",
  "price": 52,
  "nights": 1,
  "beach": "500m (up/downhill)",
  "extras": "Included",
  "rating": "8.4",
  "reviews": "100 reviews",
  "address": "SH8 RADHIME 9426, 9094 Vlora",
  "url": "https://www.booking.com/hotel/al/sirena-vlora.de.html",
  "photos": [
   "photos/hotels/mermaid-hotel-vlore/1.jpg",
   "photos/hotels/mermaid-hotel-vlore/2.jpg",
   "photos/hotels/mermaid-hotel-vlore/3.jpg",
   "photos/hotels/mermaid-hotel-vlore/4.jpg"
  ],
  "lat": 40.375,
  "lng": 19.482,
  "approx": true,
  "area": "Radhimë",
  "notes": "Up the hill behind the Radhimë strip; 500 m walk down to the water.",
  "airbnb": false
 },
 {
  "id": "duka-hotel",
  "stop": 1,
  "name": "Duka Hotel",
  "price": 105,
  "nights": 1,
  "beach": "Cross the road and youre at the beach",
  "extras": "Included. Street parking only but apparently free",
  "rating": "",
  "reviews": "",
  "address": "Rruga Murat Tërbaçi Lagjja Uji i Ftohte, 9401 Vlora",
  "url": "https://www.booking.com/hotel/al/duka-vlore1.de.html",
  "photos": [
   "photos/hotels/duka-hotel/1.jpg",
   "photos/hotels/duka-hotel/2.jpg",
   "photos/hotels/duka-hotel/3.jpg",
   "photos/hotels/duka-hotel/4.jpg",
   "photos/hotels/duka-hotel/5.jpg"
  ],
  "lat": 40.439,
  "lng": 19.4959,
  "approx": false,
  "area": "Uji i Ftohtë, Vlorë",
  "notes": "On the Lungomare, beach across the road. Location scored 9.4 by guests.",
  "airbnb": false
 },
 {
  "id": "grace-beach-front-apartement",
  "stop": 1,
  "name": "Grace Beachfront Apartment",
  "price": 54,
  "nights": 1,
  "beach": "Right at a public? Beach",
  "extras": "No and No",
  "rating": "9.4",
  "reviews": "107 reviews",
  "address": "Lagja 1 Maji, rruga sazani, Prane Pyllit te Sodes, 9401 Vlora",
  "url": "https://www.booking.com/hotel/al/grace.de.html",
  "photos": [
   "photos/hotels/grace-beach-front-apartement/1.jpg",
   "photos/hotels/grace-beach-front-apartement/2.jpg",
   "photos/hotels/grace-beach-front-apartement/3.jpg",
   "photos/hotels/grace-beach-front-apartement/4.jpg",
   "photos/hotels/grace-beach-front-apartement/5.jpg",
   "photos/hotels/grace-beach-front-apartement/6.jpg",
   "photos/hotels/grace-beach-front-apartement/7.jpg"
  ],
  "lat": 40.46,
  "lng": 19.469,
  "approx": true,
  "area": "Vlorë, Soda forest",
  "notes": "Apartment right on a public beach by Pylli i Sodës. No breakfast, no parking.",
  "airbnb": false
 },
 {
  "id": "grand-hotel-aita",
  "stop": 1,
  "name": "Grand Hotel Aita",
  "price": 85,
  "nights": 1,
  "beach": "Right at beach",
  "extras": "Included",
  "rating": "8.6",
  "reviews": "174",
  "address": "Rr. Vlore - Radhime, 1000 Vlora",
  "url": "https://www.booking.com/hotel/al/grand-atia.de.html",
  "photos": [
   "photos/hotels/grand-hotel-aita/1.jpg",
   "photos/hotels/grand-hotel-aita/2.jpg",
   "photos/hotels/grand-hotel-aita/3.jpg",
   "photos/hotels/grand-hotel-aita/4.jpg"
  ],
  "lat": 40.3553,
  "lng": 19.4833,
  "approx": false,
  "area": "Radhimë",
  "notes": "Right on the beach on the Radhimë road, sunset side.",
  "airbnb": false
 },
 {
  "id": "vala-boutqiue-hotel",
  "stop": 1,
  "name": "Vala Boutique Hotel",
  "price": 69,
  "nights": 1,
  "beach": "Beach across the road",
  "extras": "Breakfast 10 Euros, free parking",
  "rating": "8.3",
  "reviews": "400 reviews",
  "address": "Lagjia 10 Korriku, Rruga Cameria Lungomare prane Shkolles se Marines, 9401 Vlora",
  "url": "https://www.booking.com/hotel/al/vala-boutique-hotel.de.html",
  "photos": [
   "photos/hotels/vala-boutqiue-hotel/1.jpg",
   "photos/hotels/vala-boutqiue-hotel/2.jpg",
   "photos/hotels/vala-boutqiue-hotel/3.jpg",
   "photos/hotels/vala-boutqiue-hotel/4.jpg"
  ],
  "lat": 40.449,
  "lng": 19.489,
  "approx": true,
  "area": "Lungomare, Vlorë",
  "notes": "Beach across the road by the Marine school. Breakfast €10 extra, free parking.",
  "airbnb": false
 },
 {
  "id": "oasis-apart-hotel-residence-vlore",
  "stop": 1,
  "name": "Oasis Apart-Hotel Residence",
  "price": 62,
  "nights": 1,
  "beach": "Right at the beach",
  "extras": "Breakfast 7 eur, public parking",
  "rating": "7.7",
  "reviews": "900 reviews",
  "address": "Rr. Sazani, 9401 Vlora",
  "url": "https://www.booking.com/hotel/al/oasis-beach-rooms.de.html",
  "photos": [
   "photos/hotels/oasis-apart-hotel-residence-vlore/1.jpg",
   "photos/hotels/oasis-apart-hotel-residence-vlore/2.jpg",
   "photos/hotels/oasis-apart-hotel-residence-vlore/3.jpg",
   "photos/hotels/oasis-apart-hotel-residence-vlore/4.jpg",
   "photos/hotels/oasis-apart-hotel-residence-vlore/5.jpg",
   "photos/hotels/oasis-apart-hotel-residence-vlore/6.jpg",
   "photos/hotels/oasis-apart-hotel-residence-vlore/7.jpg"
  ],
  "lat": 40.4575,
  "lng": 19.4711,
  "approx": false,
  "area": "Vlorë old beach",
  "notes": "Right at the beach. Breakfast €7, public parking. Lowest review score of the list.",
  "airbnb": false
 },
 {
  "id": "veranda-boutqiue-hotel",
  "stop": 1,
  "name": "Veranda Boutique Hotel",
  "price": 75,
  "nights": 1,
  "beach": "Across teh road",
  "extras": "Included",
  "rating": "8.7",
  "reviews": "700 reviews",
  "address": "Rruga Jani Kosta Vlore, 9401 Vlora",
  "url": "https://www.booking.com/hotel/al/veranda-boutique.de.html",
  "photos": [
   "photos/hotels/veranda-boutqiue-hotel/1.jpg",
   "photos/hotels/veranda-boutqiue-hotel/2.jpg",
   "photos/hotels/veranda-boutqiue-hotel/3.jpg",
   "photos/hotels/veranda-boutqiue-hotel/4.jpg",
   "photos/hotels/veranda-boutqiue-hotel/5.jpg"
  ],
  "lat": 40.4503,
  "lng": 19.4907,
  "approx": false,
  "area": "Lungomare, Vlorë",
  "notes": "Across the road from the beach, 700 reviews at 8.7.",
  "airbnb": false
 },
 {
  "id": "anel-studio",
  "stop": 1,
  "name": "Anel Studio",
  "price": 32,
  "nights": 1,
  "beach": "300m to beach, relatively flat",
  "extras": "Included",
  "rating": "8.2",
  "reviews": "1100 reviews",
  "address": "Rruga Aleks Çaçi Building Nr 4, 9401 Vlora",
  "url": "https://www.booking.com/hotel/al/rias-hostel.de.html",
  "photos": [
   "photos/hotels/anel-studio/1.jpg",
   "photos/hotels/anel-studio/2.jpg",
   "photos/hotels/anel-studio/3.jpg",
   "photos/hotels/anel-studio/4.jpg"
  ],
  "lat": 40.4622,
  "lng": 19.4692,
  "approx": true,
  "area": "Vlorë",
  "notes": "Budget studio 300 m from the beach on flat ground. €27, or €32 with breakfast.",
  "airbnb": false
 },
 {
  "id": "safin-hotel-spa",
  "stop": 1,
  "name": "Safin Hotel & Spa",
  "price": 137,
  "nights": 1,
  "beach": "Directly at coast but people say five minute walk or golf cart shuttle?",
  "extras": "Included. Also has sauna and gym",
  "rating": "8.5",
  "reviews": "350 reviews",
  "address": "SH8, 9400 Vlora",
  "url": "https://www.booking.com/hotel/al/safin-amp-spa.de.html",
  "photos": [
   "photos/hotels/safin-hotel-spa/1.jpg",
   "photos/hotels/safin-hotel-spa/2.jpg",
   "photos/hotels/safin-hotel-spa/3.jpg",
   "photos/hotels/safin-hotel-spa/4.jpg",
   "photos/hotels/safin-hotel-spa/5.jpg"
  ],
  "lat": 40.395,
  "lng": 19.483,
  "approx": true,
  "area": "Radhimë",
  "notes": "Coast-side resort with sauna and gym. Guests mention a 5 min walk or a golf-cart shuttle to the water.",
  "airbnb": false
 },
 {
  "id": "villa-solis",
  "stop": 1,
  "name": "Villa Solis",
  "price": 50,
  "nights": 1,
  "beach": "50m",
  "extras": "included",
  "rating": "8.8",
  "reviews": "370 reviews",
  "address": "Rruga kanan maze, 9401 Vlora",
  "url": "https://www.booking.com/hotel/al/vila-anxhelo-amp-xhemi.de.html",
  "photos": [
   "photos/hotels/villa-solis/1.jpg",
   "photos/hotels/villa-solis/2.jpg",
   "photos/hotels/villa-solis/3.jpg",
   "photos/hotels/villa-solis/4.jpg",
   "photos/hotels/villa-solis/5.jpg"
  ],
  "lat": 40.435,
  "lng": 19.494,
  "approx": true,
  "area": "Uji i Ftohtë, Vlorë",
  "notes": "50 m from the water, breakfast included.",
  "airbnb": false
 },
 {
  "id": "tedis-nest",
  "stop": 1,
  "name": "Tedi's Nest",
  "price": 27,
  "nights": 1,
  "beach": "200 m",
  "extras": "No breakfast, No parking",
  "rating": "9.4",
  "reviews": "19 reviews",
  "address": "Rruga Reshat Osmani 1195, 9401 Vlora",
  "url": "https://www.booking.com/hotel/al/tedi-room.de.html",
  "photos": [
   "photos/hotels/tedis-nest/1.jpg",
   "photos/hotels/tedis-nest/2.jpg",
   "photos/hotels/tedis-nest/3.jpg"
  ],
  "lat": 40.4597,
  "lng": 19.4956,
  "approx": false,
  "area": "Vlorë",
  "notes": "Tiny, 200 m from the beach, new listing with a 9.4. No breakfast, no parking.",
  "airbnb": false
 },
 {
  "id": "toto-hotel-apartments",
  "stop": 1,
  "name": "Toto Hotel & Apartments",
  "price": 80,
  "nights": 1,
  "beach": "200m/directly across the road",
  "extras": "included",
  "rating": "8.9",
  "reviews": "1000 reviews",
  "address": "Rr. \"Sali Vranishti\" Prane plazhit \"KALAJA\", 9400 Vlora",
  "url": "https://www.booking.com/hotel/al/toto-residence-apartments-with-sea-view.de.html",
  "photos": [
   "photos/hotels/toto-hotel-apartments/1.jpg",
   "photos/hotels/toto-hotel-apartments/2.jpg",
   "photos/hotels/toto-hotel-apartments/3.jpg",
   "photos/hotels/toto-hotel-apartments/4.jpg"
  ],
  "lat": 40.393,
  "lng": 19.482,
  "approx": true,
  "area": "Radhimë (Kalaja beach)",
  "notes": "Directly across the road from Kalaja beach, breakfast included.",
  "airbnb": false
 },
 {
  "id": "marina-premium-beach-hotel-apartments",
  "stop": 1,
  "name": "Marina Premium Beach Hotel",
  "price": 52,
  "nights": 1,
  "beach": "close?",
  "extras": "Breakfast 5eur, public parking",
  "rating": "8.3",
  "reviews": "1000+",
  "address": "Lungomare, vlore marina, 0033 Vlora",
  "url": "https://www.booking.com/hotel/al/marina-premium.de.html",
  "photos": [
   "photos/hotels/marina-premium-beach-hotel-apartments/1.jpg",
   "photos/hotels/marina-premium-beach-hotel-apartments/2.jpg"
  ],
  "lat": 40.4446,
  "lng": 19.4953,
  "approx": false,
  "area": "Vlorë marina",
  "notes": "On the Lungomare by the marina. Breakfast €5, public parking.",
  "airbnb": false
 },
 {
  "id": "azora-beach-hotel",
  "stop": 1,
  "name": "Azora Beach Hotel",
  "price": 169,
  "nights": 1,
  "beach": "At the bach",
  "extras": "included",
  "rating": "8.7",
  "reviews": "50 reviews",
  "address": "Zanzara Beach Bar, 9405 Vlora",
  "url": "https://www.booking.com/hotel/al/azora-beach.html",
  "photos": [
   "photos/hotels/azora-beach-hotel/1.jpg",
   "photos/hotels/azora-beach-hotel/2.jpg",
   "photos/hotels/azora-beach-hotel/3.jpg",
   "photos/hotels/azora-beach-hotel/4.jpg"
  ],
  "lat": 40.381,
  "lng": 19.484,
  "approx": true,
  "area": "Radhimë",
  "notes": "The arrival treat from the plan: balcony straight over the bay to Karaburun, own beach deck with cabanas for guests. Newest and most polished.",
  "airbnb": false
 },
 {
  "id": "azar-luxury-suites",
  "stop": 1,
  "name": "Azar Luxury Suites",
  "price": 74,
  "nights": 1,
  "beach": "close",
  "extras": "Breakfast 4 euro, parking included",
  "rating": "8.8",
  "reviews": "1000+",
  "address": "Rruga Aleksandër Moisiu, 9402 Vlora",
  "url": "https://www.booking.com/hotel/al/azar-luxury-suites.html",
  "photos": [
   "photos/hotels/azar-luxury-suites/1.jpg",
   "photos/hotels/azar-luxury-suites/2.jpg",
   "photos/hotels/azar-luxury-suites/3.jpg",
   "photos/hotels/azar-luxury-suites/4.jpg",
   "photos/hotels/azar-luxury-suites/5.jpg"
  ],
  "lat": 40.4252,
  "lng": 19.4913,
  "approx": false,
  "area": "Uji i Ftohtë, Vlorë",
  "notes": "Infinity pool over the sea, private beach with free sunbeds, sea-view suites. Breakfast €4, parking included.",
  "airbnb": false
 },
 {
  "id": "blue-pines-villa",
  "stop": 1,
  "name": "Blue Pines Villa",
  "price": 30,
  "nights": 1,
  "beach": "close",
  "extras": "included",
  "rating": "8.3",
  "reviews": "600 reviews",
  "address": "Rr. Sazani, 9401 Vlora",
  "url": "https://www.booking.com/hotel/al/blue-pines-villa.de.html",
  "photos": [
   "photos/hotels/blue-pines-villa/1.jpg",
   "photos/hotels/blue-pines-villa/2.jpg"
  ],
  "lat": 40.457,
  "lng": 19.4715,
  "approx": true,
  "area": "Vlorë old beach",
  "notes": "Cheapest bed on the coast, close to the beach, breakfast included.",
  "airbnb": false
 },
 {
  "id": "sea-and-sand-hotel",
  "stop": 1,
  "name": "Sea and Sand Hotel",
  "price": 106,
  "nights": 1,
  "beach": "At it",
  "extras": "Included",
  "rating": "8.4",
  "reviews": "2000 reviews",
  "address": "Rr. Sazani Old Beach, 9404 Vlora",
  "url": "https://www.booking.com/hotel/al/sea-amp-sand.html",
  "photos": [
   "photos/hotels/sea-and-sand-hotel/1.jpg",
   "photos/hotels/sea-and-sand-hotel/2.jpg",
   "photos/hotels/sea-and-sand-hotel/3.jpg",
   "photos/hotels/sea-and-sand-hotel/4.jpg",
   "photos/hotels/sea-and-sand-hotel/5.jpg",
   "photos/hotels/sea-and-sand-hotel/6.jpg"
  ],
  "lat": 40.455,
  "lng": 19.474,
  "approx": true,
  "area": "Vlorë old beach",
  "notes": "Big beachfront hotel, 2000 reviews, breakfast included.",
  "airbnb": false
 },
 {
  "id": "mazarine-hotel-vlore-albania",
  "stop": 1,
  "name": "Mazarine Hotel",
  "price": 134,
  "nights": 1,
  "beach": "direct",
  "extras": "included",
  "rating": "9.2",
  "reviews": "1000+ reviews",
  "address": "Rruga Sali Vranishti, 9404 Vlora",
  "url": "https://www.booking.com/hotel/al/mazarine.html",
  "photos": [
   "photos/hotels/mazarine-hotel-vlore-albania/1.jpg",
   "photos/hotels/mazarine-hotel-vlore-albania/2.jpg",
   "photos/hotels/mazarine-hotel-vlore-albania/3.jpg",
   "photos/hotels/mazarine-hotel-vlore-albania/4.jpg",
   "photos/hotels/mazarine-hotel-vlore-albania/5.jpg"
  ],
  "lat": 40.3906,
  "lng": 19.4816,
  "approx": false,
  "area": "Radhimë",
  "notes": "Newer hotel with pool and sunset balconies, directly on the water. 9.2 from 1000+ reviews.",
  "airbnb": false
 },
 {
  "id": "la-brisa-boutique-hotel",
  "stop": 2,
  "name": "La Brisa Boutique Hotel",
  "price": 374,
  "nights": 2,
  "beach": "direct",
  "extras": "included",
  "rating": "8.2",
  "reviews": "600 reviews",
  "address": "Rruga Jaliskari 8401, Dhërmi 8401, 8401 Dhërmi",
  "url": "https://www.booking.com/hotel/al/la-brisa-boutique.de.html",
  "photos": [
   "photos/hotels/la-brisa-boutique-hotel/1.jpg",
   "photos/hotels/la-brisa-boutique-hotel/2.jpg",
   "photos/hotels/la-brisa-boutique-hotel/3.jpg"
  ],
  "lat": 40.141,
  "lng": 19.64,
  "approx": true,
  "area": "Dhërmi beach (Jaliskari)",
  "notes": "Rooftop infinity pool, spa, sunsets, modern design. The Dhërmi splurge.",
  "airbnb": false
 },
 {
  "id": "empire-beach-resort-adults-only",
  "stop": 2,
  "name": "Empire Beach Resort (adults only)",
  "price": 292,
  "nights": 2,
  "beach": "direct",
  "extras": "included",
  "rating": "8.7",
  "reviews": "1000+ reviews",
  "address": "Empire Beach Resort, Posta kufitare Dhermi, 9422 Dhërmi",
  "url": "https://www.booking.com/hotel/al/empire-beach-resort-dhermi.de.html",
  "photos": [
   "photos/hotels/empire-beach-resort-adults-only/1.jpg",
   "photos/hotels/empire-beach-resort-adults-only/2.jpg",
   "photos/hotels/empire-beach-resort-adults-only/3.jpg"
  ],
  "lat": 40.146,
  "lng": 19.6264,
  "approx": false,
  "area": "Dhërmi beach",
  "notes": "Adults-only resort directly on the beach, breakfast included.",
  "airbnb": false
 },
 {
  "id": "hotel-azure",
  "stop": 2,
  "name": "Hotel Azure",
  "price": 64,
  "nights": 2,
  "beach": "100m",
  "extras": "no",
  "rating": "7.9",
  "reviews": "200+ reviews",
  "address": "Kamping Pa Emer, 9422 Dhërmi",
  "url": "https://www.booking.com/hotel/al/azure.de.html",
  "photos": [
   "photos/hotels/hotel-azure/1.jpg",
   "photos/hotels/hotel-azure/2.jpg",
   "photos/hotels/hotel-azure/3.jpg"
  ],
  "lat": 40.152,
  "lng": 19.617,
  "approx": true,
  "area": "Drymades",
  "notes": "100 m from Drymades beach, no breakfast. Cheapest Dhërmi option.",
  "airbnb": false
 },
 {
  "id": "essos-villas",
  "stop": 2,
  "name": "Essos Villas",
  "price": 110,
  "nights": 2,
  "beach": "unclear",
  "extras": "no",
  "rating": "9.1",
  "reviews": "700 reviews",
  "address": "Rruga Megali Hora, Dhërmi",
  "url": "https://www.booking.com/hotel/al/jonev-beach-villas.de.html",
  "photos": [
   "photos/hotels/essos-villas/1.jpg",
   "photos/hotels/essos-villas/2.jpg",
   "photos/hotels/essos-villas/3.jpg",
   "photos/hotels/essos-villas/4.jpg"
  ],
  "lat": 40.1446,
  "lng": 19.6319,
  "approx": false,
  "area": "Dhërmi",
  "notes": "Villas on Rruga Megali Hora, guests rate the location 9.3. No breakfast.",
  "airbnb": false
 },
 {
  "id": "casa-boha",
  "stop": 2,
  "name": "Casa Boha",
  "price": 180,
  "nights": 2,
  "beach": "Further (drivign distance=",
  "extras": "included",
  "rating": "9.2",
  "reviews": "250 reviews",
  "address": "Rruga Perivolo, 9422 Dhërmi",
  "url": "https://www.booking.com/hotel/al/casa-boha.de.html",
  "photos": [
   "photos/hotels/casa-boha/1.jpg",
   "photos/hotels/casa-boha/2.jpg",
   "photos/hotels/casa-boha/3.jpg"
  ],
  "lat": 40.1551,
  "lng": 19.6108,
  "approx": true,
  "area": "Perivolo / Drymades",
  "notes": "Design guesthouse on Rruga Perivolo, driving distance to the beach, breakfast included.",
  "airbnb": false
 },
 {
  "id": "gogos",
  "stop": 2,
  "name": "Gogo's Boutique Hotel",
  "price": 167,
  "nights": 2,
  "beach": "Further (driving)",
  "extras": "included",
  "rating": "9.0",
  "reviews": "1700 reviews",
  "address": "68 Rruga Perivolo, 9422 Dhërmi",
  "url": "https://www.booking.com/hotel/al/gogo-39-s-boutique.de.html",
  "photos": [
   "photos/hotels/gogos/1.jpg",
   "photos/hotels/gogos/2.jpg",
   "photos/hotels/gogos/3.jpg",
   "photos/hotels/gogos/4.jpg"
  ],
  "lat": 40.1551,
  "lng": 19.621,
  "approx": false,
  "area": "Perivolo / Drymades",
  "notes": "1700 reviews at 9.0, breakfast included, a short drive to the beach.",
  "airbnb": false
 },
 {
  "id": "old-town-hotel-dhermi",
  "stop": 2,
  "name": "Old Town Hotel Dhermi",
  "price": 90,
  "nights": 2,
  "beach": "Further (driving)",
  "extras": "",
  "rating": "8.6",
  "reviews": "375 reviews",
  "address": "Sheshi Petrro Marko 1, 1001 Dhërmi",
  "url": "https://www.booking.com/hotel/al/old-town-dhermi.de.html",
  "photos": [
   "photos/hotels/old-town-hotel-dhermi/1.jpg",
   "photos/hotels/old-town-hotel-dhermi/2.jpg",
   "photos/hotels/old-town-hotel-dhermi/3.jpg"
  ],
  "lat": 40.1517,
  "lng": 19.6402,
  "approx": true,
  "area": "Old Dhërmi village",
  "notes": "Up in the old stone village, sunset evenings on the doorstep. Driving to the beach.",
  "airbnb": false
 },
 {
  "id": "duni-s-104",
  "stop": 2,
  "name": "Duni's 104 (Airbnb)",
  "price": 86,
  "nights": 2,
  "beach": "driving",
  "extras": "No, parking yes",
  "rating": "4.92",
  "reviews": "26 reviews",
  "address": "North Gjilekë close to the Sh8",
  "url": "https://www.airbnb.de/rooms/1687776701708003676",
  "photos": [
   "photos/hotels/duni-s-104/1.jpg"
  ],
  "lat": 40.1555,
  "lng": 19.6314,
  "approx": true,
  "area": "Gjilekë",
  "notes": "Airbnb in Gjilekë just off the SH8 above Dhërmi. Parking, no breakfast.",
  "airbnb": true
 },
 {
  "id": "sun-george",
  "stop": 3,
  "name": "Sun George Hotel",
  "price": 122,
  "nights": 2,
  "beach": "driving",
  "extras": "no",
  "rating": "9.1",
  "reviews": "500 reviews",
  "address": "SH8, 9456 Himarë",
  "url": "https://www.booking.com/hotel/al/sun-george-himare.de.html",
  "photos": [
   "photos/hotels/sun-george/1.jpg",
   "photos/hotels/sun-george/2.jpg"
  ],
  "lat": 40.1135,
  "lng": 19.7375,
  "approx": true,
  "area": "Above Himarë / Livadhi",
  "notes": "Sea-view hotel on the SH8 north of town, near Livadhi beach. Driving to the beach, no breakfast.",
  "airbnb": false
 },
 {
  "id": "emily-hotel",
  "stop": 3,
  "name": "Emily's Hotel",
  "price": 200,
  "nights": 2,
  "beach": "At the beach",
  "extras": "no",
  "rating": "9.1",
  "reviews": "500 reviews",
  "address": "St.Andre Dhima 4, 9425 Himarë",
  "url": "https://www.booking.com/hotel/al/emilys-himare.de.html",
  "photos": [
   "photos/hotels/emily-hotel/1.jpg",
   "photos/hotels/emily-hotel/2.jpg"
  ],
  "lat": 40.102,
  "lng": 19.7455,
  "approx": true,
  "area": "Himarë beach",
  "notes": "Right on Himarë town beach, location rated 9.6. No breakfast.",
  "airbnb": false
 },
 {
  "id": "pine-side-camp-tent",
  "stop": 3,
  "name": "Pine Side Camp (glamping tent)",
  "price": 50,
  "nights": 2,
  "beach": "At the beach",
  "extras": "Parking included",
  "rating": "9.3",
  "reviews": "1500+reviews",
  "address": "Close to Rr.Hali, 9425 Himarë",
  "url": "https://www.booking.com/hotel/al/pine-side.de.html",
  "photos": [
   "photos/hotels/pine-side-camp-tent/1.jpg",
   "photos/hotels/pine-side-camp-tent/2.jpg",
   "photos/hotels/pine-side-camp-tent/3.jpg",
   "photos/hotels/pine-side-camp-tent/4.jpg"
  ],
  "lat": 40.099,
  "lng": 19.7397,
  "approx": false,
  "area": "Potami beach, Himarë",
  "notes": "Glamping tent under the pines on the beach. 9.3 from 1500+ reviews. The wild-card.",
  "airbnb": false
 },
 {
  "id": "life-on-green",
  "stop": 3,
  "name": "The Life on Green",
  "price": 126,
  "nights": 2,
  "beach": "At the beach",
  "extras": "Parking included",
  "rating": "8.9",
  "reviews": "212 reviews",
  "address": "Rr.Hali, 9425 Himarë",
  "url": "https://www.booking.com/hotel/al/the-life-on-green.de.html",
  "photos": [
   "photos/hotels/life-on-green/1.jpg",
   "photos/hotels/life-on-green/2.jpg",
   "photos/hotels/life-on-green/3.jpg"
  ],
  "lat": 40.0985,
  "lng": 19.7405,
  "approx": true,
  "area": "Potami beach, Himarë",
  "notes": "Green garden setting at the beach, parking included.",
  "airbnb": false
 },
 {
  "id": "ionio-blue",
  "stop": 3,
  "name": "Ionio Blue Rooms",
  "price": 180,
  "nights": 2,
  "beach": "100m",
  "extras": "Included, no parking",
  "rating": "9.3",
  "reviews": "77 reviews",
  "address": "Stefaneli, 9425 Himarë",
  "url": "https://www.booking.com/hotel/al/ionio-rooms-himara7.de.html",
  "photos": [
   "photos/hotels/ionio-blue/1.jpg"
  ],
  "lat": 40.0999,
  "lng": 19.7501,
  "approx": true,
  "area": "Himarë",
  "notes": "100 m from the beach, breakfast included, no parking.",
  "airbnb": false
 },
 {
  "id": "kerculla-resort",
  "stop": 4,
  "name": "Kerculla Resort",
  "price": 150,
  "nights": 1,
  "beach": "Not a beach region",
  "extras": "included",
  "rating": "9.4",
  "reviews": "1000 reviews",
  "address": "RRUGA BASHKIM KOKONA, 6001 Gjirokastra",
  "url": "https://www.booking.com/hotel/al/kerculla-resort.de.html",
  "photos": [
   "photos/hotels/kerculla-resort/1.jpg",
   "photos/hotels/kerculla-resort/2.jpg",
   "photos/hotels/kerculla-resort/3.jpg"
  ],
  "lat": 40.0731,
  "lng": 20.1321,
  "approx": false,
  "area": "Hillside above Gjirokastër",
  "notes": "Pool with the castle and valley below, steam room. Rated 9.4 by 1000 guests. The mountain splurge.",
  "airbnb": false
 },
 {
  "id": "trigona-guest-house-hostel",
  "stop": 4,
  "name": "Trigona Guest House",
  "price": 26,
  "nights": 1,
  "beach": "Not a beach region",
  "extras": "no",
  "rating": "9.0",
  "reviews": "500 reviews",
  "address": "Rruga Alqi Kondi, 6001 Gjirokastra",
  "url": "https://www.booking.com/hotel/al/trigona-hostel.de.html",
  "photos": [
   "photos/hotels/trigona-guest-house-hostel/1.jpg",
   "photos/hotels/trigona-guest-house-hostel/2.jpg",
   "photos/hotels/trigona-guest-house-hostel/3.jpg"
  ],
  "lat": 40.0781,
  "lng": 20.1419,
  "approx": false,
  "area": "Gjirokastër old town",
  "notes": "Guest house rooms at hostel prices, location 9.4. No breakfast.",
  "airbnb": false
 },
 {
  "id": "guest-house-memushi",
  "stop": 4,
  "name": "Guest House Memushi",
  "price": 40,
  "nights": 1,
  "beach": "Good location",
  "extras": "included",
  "rating": "9.4",
  "reviews": "600 reviews",
  "address": "",
  "url": "https://www.booking.com/hotel/al/taverna-memushi.de.html",
  "photos": [
   "photos/hotels/guest-house-memushi/1.jpg",
   "photos/hotels/guest-house-memushi/2.jpg",
   "photos/hotels/guest-house-memushi/3.jpg",
   "photos/hotels/guest-house-memushi/4.jpg"
  ],
  "lat": 40.0758,
  "lng": 20.1324,
  "approx": false,
  "area": "Gjirokastër old town",
  "notes": "Family guest house with its own taverna, breakfast included.",
  "airbnb": false
 },
 {
  "id": "old-street-villa",
  "stop": 4,
  "name": "Old Street Villa",
  "price": 54,
  "nights": 1,
  "beach": "Nota beach area",
  "extras": "incldued",
  "rating": "9.3",
  "reviews": "157 reviews",
  "address": "Rruga Ropi Jani, 6002 Gjirokastra",
  "url": "https://www.booking.com/hotel/al/old-street-villa.de.html",
  "photos": [
   "photos/hotels/old-street-villa/1.jpg",
   "photos/hotels/old-street-villa/2.jpg",
   "photos/hotels/old-street-villa/3.jpg",
   "photos/hotels/old-street-villa/4.jpg"
  ],
  "lat": 40.0777,
  "lng": 20.1379,
  "approx": false,
  "area": "Gjirokastër old town",
  "notes": "Restored villa in the old streets, breakfast included, 9.3.",
  "airbnb": false
 },
 {
  "id": "palorto-inn",
  "stop": 4,
  "name": "Palorto Inn",
  "price": 101,
  "nights": 1,
  "beach": "Not a beach region",
  "extras": "included",
  "rating": "9.4",
  "reviews": "381 reviews",
  "address": "Rruga Hysen Hoxha 11, 6001 Gjirokastra",
  "url": "https://www.booking.com/hotel/al/palorto-inn-boutique.de.html",
  "photos": [
   "photos/hotels/palorto-inn/1.jpg",
   "photos/hotels/palorto-inn/2.jpg",
   "photos/hotels/palorto-inn/3.jpg",
   "photos/hotels/palorto-inn/4.jpg"
  ],
  "lat": 40.0776,
  "lng": 20.1323,
  "approx": false,
  "area": "Palorto, Gjirokastër",
  "notes": "Boutique inn in the Palorto quarter, breakfast included, 9.4.",
  "airbnb": false
 },
 {
  "id": "stemalu-hotel-doppelzimmer",
  "stop": 4,
  "name": "Stemalu Hotel (Airbnb)",
  "price": 29,
  "nights": 1,
  "beach": "Not a beach region",
  "extras": "no",
  "rating": "5.0",
  "reviews": "2 reviews",
  "address": "34JW+2G4, Rruga 7 Kronjte, Gjirokastër 6002",
  "url": "https://www.airbnb.de/rooms/1758708151169691994",
  "photos": [
   "photos/hotels/stemalu-hotel-doppelzimmer/1.jpg",
   "photos/hotels/stemalu-hotel-doppelzimmer/2.jpg",
   "photos/hotels/stemalu-hotel-doppelzimmer/3.jpg",
   "photos/hotels/stemalu-hotel-doppelzimmer/4.jpg"
  ],
  "lat": 40.0766,
  "lng": 20.1409,
  "approx": true,
  "area": "Gjirokastër",
  "notes": "Airbnb double room, very new listing (2 reviews).",
  "airbnb": true
 },
 {
  "id": "sonnendurchflutete-wohnung-mit-garten-ku",
  "stop": 4,
  "name": "Sunny garden apartment (Airbnb)",
  "price": 37,
  "nights": 1,
  "beach": "NA",
  "extras": "included",
  "rating": "4.96",
  "reviews": "73 reviews",
  "address": "Rruga Reshat Isufati Gjirokastër 6002",
  "url": "https://www.airbnb.de/rooms/1452671273270771338",
  "photos": [
   "photos/hotels/sonnendurchflutete-wohnung-mit-garten-ku/1.jpg",
   "photos/hotels/sonnendurchflutete-wohnung-mit-garten-ku/2.jpg",
   "photos/hotels/sonnendurchflutete-wohnung-mit-garten-ku/3.jpg"
  ],
  "lat": 40.0758,
  "lng": 20.1486,
  "approx": false,
  "area": "Gjirokastër",
  "notes": "Airbnb apartment with garden, kitchen and free parking. 4.96 from 73 reviews.",
  "airbnb": true
 },
 {
  "id": "vila-24-deluxe-doppelzimmer",
  "stop": 4,
  "name": "Vila 24, deluxe double (Airbnb)",
  "price": 36,
  "nights": 1,
  "beach": "NA",
  "extras": "Free parking",
  "rating": "4.87",
  "reviews": "30 reviews",
  "address": "Rruga Astrit Toto",
  "url": "https://www.airbnb.de/rooms/1429566708195266806",
  "photos": [
   "photos/hotels/vila-24-deluxe-doppelzimmer/1.jpg",
   "photos/hotels/vila-24-deluxe-doppelzimmer/2.jpg",
   "photos/hotels/vila-24-deluxe-doppelzimmer/3.jpg"
  ],
  "lat": 40.0774,
  "lng": 20.1352,
  "approx": false,
  "area": "Gjirokastër",
  "notes": "Airbnb deluxe double with free parking. 4.87 from 30 reviews.",
  "airbnb": true
 },
 {
  "id": "farma-sotira",
  "stop": 5,
  "name": "Farma Sotira",
  "price": 50,
  "nights": 1,
  "beach": "Farm, rural area. Also cooking/dinner supposed to be good. They have horses",
  "extras": "included",
  "rating": "8.8",
  "reviews": "151 reviews",
  "address": "Rruga Nacionale Erseke - Leskovik, 7401 Erseke Albania, 7402 Leskovik",
  "url": "https://www.booking.com/hotel/al/farma-sotira.de.html",
  "photos": [
   "photos/hotels/farma-sotira/1.jpg",
   "photos/hotels/farma-sotira/2.jpg",
   "photos/hotels/farma-sotira/3.jpg",
   "photos/hotels/farma-sotira/4.jpg"
  ],
  "lat": 40.2147,
  "lng": 20.6465,
  "approx": false,
  "area": "Leskovik, 45 min from Bënjë",
  "notes": "Wooden cabins on a working farm: own trout, garden vegetables, pool, horse riding. Book the dinner with the cabin.",
  "airbnb": false
 },
 {
  "id": "melesin-distillery",
  "stop": 5,
  "name": "Melesin Distillery",
  "price": 96,
  "nights": 1,
  "beach": "NA",
  "extras": "included",
  "rating": "9.6",
  "reviews": "500+ reviews",
  "address": "Rruga Faik Konica Ndertesa nr.5, 7402 Leskovik",
  "url": "https://www.booking.com/hotel/al/melesin-distillery.de.html",
  "photos": [
   "photos/hotels/melesin-distillery/1.jpg",
   "photos/hotels/melesin-distillery/2.jpg",
   "photos/hotels/melesin-distillery/3.jpg",
   "photos/hotels/melesin-distillery/4.jpg"
  ],
  "lat": 40.1528,
  "lng": 20.5992,
  "approx": false,
  "area": "Leskovik",
  "notes": "Boutique rooms at a raki distillery, 9.6 from 500+ reviews. Breakfast included.",
  "airbnb": false
 },
 {
  "id": "l-e-mom-apart-hotel",
  "stop": 6,
  "name": "Le Mom Apart Hotel",
  "price": 47,
  "nights": 1,
  "beach": "NA",
  "extras": "included",
  "rating": "9.7",
  "reviews": "300+reviews",
  "address": "Rruga Antipatrea 1, 5003 Berat",
  "url": "https://www.booking.com/hotel/al/lemom-apart.de.html",
  "photos": [
   "photos/hotels/l-e-mom-apart-hotel/1.jpg",
   "photos/hotels/l-e-mom-apart-hotel/2.jpg",
   "photos/hotels/l-e-mom-apart-hotel/3.jpg",
   "photos/hotels/l-e-mom-apart-hotel/4.jpg"
  ],
  "lat": 40.6986,
  "lng": 19.9731,
  "approx": false,
  "area": "Berat (Uznovë)",
  "notes": "Apart-hotel on the main road, 9.7 from 300+ reviews, breakfast included. Slightly out of the old town.",
  "airbnb": false
 },
 {
  "id": "ador-boutique-hotel",
  "stop": 6,
  "name": "Ador Boutique Hotel",
  "price": 50,
  "nights": 1,
  "beach": "NA",
  "extras": "included",
  "rating": "9.5",
  "reviews": "400+ reviews",
  "address": "Rruga Jani Kosta, 5001 Berat",
  "url": "https://www.booking.com/hotel/al/ador-boutique.de.html",
  "photos": [
   "photos/hotels/ador-boutique-hotel/1.jpg",
   "photos/hotels/ador-boutique-hotel/2.jpg"
  ],
  "lat": 40.7033,
  "lng": 19.9475,
  "approx": false,
  "area": "Gorica, Berat",
  "notes": "Boutique hotel on the Gorica side with the classic view across the river. 9.5.",
  "airbnb": false
 },
 {
  "id": "hotel-villa-edis",
  "stop": 6,
  "name": "Hotel Villa Edis",
  "price": 31,
  "nights": 1,
  "beach": "NA",
  "extras": "included",
  "rating": "9.4",
  "reviews": "700+reveiws",
  "address": "Rruga Shkembi, 5001 Berat",
  "url": "https://www.booking.com/hotel/al/villa-edis.de.html",
  "photos": [
   "photos/hotels/hotel-villa-edis/1.jpg",
   "photos/hotels/hotel-villa-edis/2.jpg",
   "photos/hotels/hotel-villa-edis/3.jpg"
  ],
  "lat": 40.7109,
  "lng": 19.9463,
  "approx": true,
  "area": "Berat",
  "notes": "Cheap and cheerful, 9.4 from 700+ reviews, breakfast included.",
  "airbnb": false
 },
 {
  "id": "tradita-e-beratit",
  "stop": 6,
  "name": "Tradita e Beratit",
  "price": 72,
  "nights": 1,
  "beach": "Planned maybe to have dinner ~€28 set menu for two — traditional degustation. But also some nice alternatives…uff.",
  "extras": "included",
  "rating": "8.7",
  "reviews": "900+reviews",
  "address": "Rruga Stiliano Bandilli, 5001 Berat",
  "url": "https://www.booking.com/hotel/al/tradita-e-beratit-berat.de.html",
  "photos": [
   "photos/hotels/tradita-e-beratit/1.jpg",
   "photos/hotels/tradita-e-beratit/2.jpg",
   "photos/hotels/tradita-e-beratit/3.jpg",
   "photos/hotels/tradita-e-beratit/4.jpg",
   "photos/hotels/tradita-e-beratit/5.jpg"
  ],
  "lat": 40.7026,
  "lng": 19.9461,
  "approx": false,
  "area": "Gorica, Berat",
  "notes": "Restored Ottoman villa, traditional tasting dinner downstairs (~€28 for two), petulla breakfast. The stay-and-eat pick.",
  "airbnb": false
 },
 {
  "id": "mattis-hotel",
  "stop": 7,
  "name": "Mattis Hotel",
  "price": 156,
  "nights": 1,
  "beach": "",
  "extras": "included",
  "rating": "8.8",
  "reviews": "350 reviews",
  "address": "Rruga Hafiz Ibrahim Dalliu, 1017 Tirana",
  "url": "https://www.booking.com/hotel/al/mattis.de.html",
  "photos": [
   "photos/hotels/mattis-hotel/1.jpg",
   "photos/hotels/mattis-hotel/2.jpg",
   "photos/hotels/mattis-hotel/3.jpg"
  ],
  "lat": 41.3384,
  "lng": 19.826,
  "approx": true,
  "area": "Central Tirana",
  "notes": "Polished central hotel, breakfast included. 8.8 from 350 reviews.",
  "airbnb": false
 },
 {
  "id": "e-88-hotel",
  "stop": 7,
  "name": "E-88 Hotel",
  "price": 63,
  "nights": 1,
  "beach": "",
  "extras": "Parking yes",
  "rating": "",
  "reviews": "",
  "address": "Rruga Dritan Hoxha, 1001 Tirana",
  "url": "https://www.booking.com/hotel/al/e-88.de.html",
  "photos": [
   "photos/hotels/e-88-hotel/1.jpg",
   "photos/hotels/e-88-hotel/2.jpg",
   "photos/hotels/e-88-hotel/3.jpg"
  ],
  "lat": 41.3334,
  "lng": 19.8033,
  "approx": true,
  "area": "Tirana (west)",
  "notes": "Mid-range hotel on Rruga Dritan Hoxha with parking.",
  "airbnb": false
 },
 {
  "id": "hotel-colis",
  "stop": 7,
  "name": "Hotel Coli's",
  "price": 45,
  "nights": 1,
  "beach": "",
  "extras": "included",
  "rating": "8.4",
  "reviews": "2000 reviews",
  "address": "Str Iliria (Donald Trump) Kamez ,Tirane, 1001 Tirana",
  "url": "https://www.booking.com/hotel/al/coli-39-s-group.de.html",
  "photos": [
   "photos/hotels/hotel-colis/1.jpg",
   "photos/hotels/hotel-colis/2.jpg",
   "photos/hotels/hotel-colis/3.jpg"
  ],
  "lat": 41.372,
  "lng": 19.7582,
  "approx": false,
  "area": "Kamëz",
  "notes": "Between Tirana and the airport, breakfast included, 2000 reviews.",
  "airbnb": false
 },
 {
  "id": "oli-hotel",
  "stop": 7,
  "name": "OLI Hotel",
  "price": 49,
  "nights": 1,
  "beach": "",
  "extras": "included",
  "rating": "9.4",
  "reviews": "300 reviews",
  "address": "38 Rruga e Krujes, 1502 Fushë-Krujë",
  "url": "https://www.booking.com/hotel/al/oli-fushe-kruje.de.html",
  "photos": [
   "photos/hotels/oli-hotel/1.jpg",
   "photos/hotels/oli-hotel/2.jpg"
  ],
  "lat": 41.4785,
  "lng": 19.718,
  "approx": true,
  "area": "Fushë-Krujë",
  "notes": "10 min from the airport, 9.4 from 300 reviews, breakfast included.",
  "airbnb": false
 },
 {
  "id": "hotel-triada",
  "stop": 7,
  "name": "Hotel Triada",
  "price": 45,
  "nights": 1,
  "beach": "",
  "extras": "No, parking yes",
  "rating": "8.8",
  "reviews": "200 reviews",
  "address": "Rruga e Krujes, Fushë-Krujë",
  "url": "https://www.booking.com/hotel/al/triada-fushe-kruje1.de.html",
  "photos": [
   "photos/hotels/hotel-triada/1.jpg",
   "photos/hotels/hotel-triada/2.jpg"
  ],
  "lat": 41.478,
  "lng": 19.72,
  "approx": true,
  "area": "Fushë-Krujë",
  "notes": "10 min from the airport, parking, no breakfast.",
  "airbnb": false
 },
 {
  "id": "marina-suites-by-premium-selection",
  "stop": 7,
  "name": "Marina Suites by Premium Selection",
  "price": 157,
  "nights": 1,
  "beach": "",
  "extras": "no",
  "rating": "8.2",
  "reviews": "250 reviews",
  "address": "Rruga Taulantia, 2001 Durrës",
  "url": "https://www.booking.com/hotel/al/marina-luxury-suites-by-ps.de.html",
  "photos": [
   "photos/hotels/marina-suites-by-premium-selection/1.jpg",
   "photos/hotels/marina-suites-by-premium-selection/2.jpg",
   "photos/hotels/marina-suites-by-premium-selection/3.jpg"
  ],
  "lat": 41.3099,
  "lng": 19.4446,
  "approx": false,
  "area": "Durrës seafront",
  "notes": "Sea-view suites on the Durrës promenade. 35 min to the airport.",
  "airbnb": false
 },
 {
  "id": "perlas-aprtment-durres-center",
  "stop": 7,
  "name": "Perlas Apartment, Durrës centre",
  "price": 39,
  "nights": 1,
  "beach": "",
  "extras": "no",
  "rating": "10",
  "reviews": "11 reveiws",
  "address": "Rruga Petraq Boshnjaku, 2001 Durrës",
  "url": "https://www.booking.com/hotel/al/perlas-apartment-durres-centre.de.html",
  "photos": [
   "photos/hotels/perlas-aprtment-durres-center/1.jpg",
   "photos/hotels/perlas-aprtment-durres-center/2.jpg",
   "photos/hotels/perlas-aprtment-durres-center/3.jpg"
  ],
  "lat": 41.3226,
  "lng": 19.4466,
  "approx": true,
  "area": "Durrës centre",
  "notes": "Apartment in the centre, 10 from 11 reviews.",
  "airbnb": false
 }
];